version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    labels:
      - dependencies
      - github-actions
    assignees:
      - ptt3199

  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    assignees:
      - ptt3199
    open-pull-requests-limit: 5